version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    volumes:
      - ./api:/app/api
      - ./src:/app/src
    command: bash -c "cd /app/api && python quantum_api.py"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    image: python:3.11-slim
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/app
    working_dir: /app
    command: python -m http.server 8080
    depends_on:
      - backend

networks:
  default:
    name: quantum-network
