#!/bin/bash
# 🎯 QUICK REFERENCE CARD - COPY & PASTE THESE COMMANDS

echo ""
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                                                                    ║"
echo "║  🚀 QUANTUM SIMULATOR - QUICK REFERENCE                           ║"
echo "║                                                                    ║"
echo "║  HOW TO RUN BOTH BACKEND & FRONTEND                               ║"
echo "║                                                                    ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 OPTION 1: START EVERYTHING WITH ONE COMMAND"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   bash /workspaces/animation_quantum_mech_basics/start_all.sh"
echo ""
echo "   Then:"
echo "   1. Open PORTS panel (bottom of VS Code)"
echo "   2. Click globe 🌐 next to port 8000"
echo "   3. Your dashboard opens!"
echo ""
echo ""

echo "📋 OPTION 2: THREE TERMINALS (More Control)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   TERMINAL 1 - Start Backend:"
echo "   ┌──────────────────────────────────────────────────────────┐"
echo "   │ cd /workspaces/animation_quantum_mech_basics             │"
echo "   │ source .venv/bin/activate                               │"
echo "   │ PYTHONPATH=./src python app/backend/app/api/enhanced_api.py │"
echo "   └──────────────────────────────────────────────────────────┘"
echo ""
echo "   TERMINAL 2 - Start Frontend:"
echo "   ┌──────────────────────────────────────────────────────────┐"
echo "   │ cd /workspaces/animation_quantum_mech_basics/app/frontend/public │"
echo "   │ python -m http.server 8000                              │"
echo "   └──────────────────────────────────────────────────────────┘"
echo ""
echo "   TERMINAL 3 - Open Browser:"
echo "   ┌──────────────────────────────────────────────────────────┐"
echo "   │ http://localhost:8000/dashboard.html                    │"
echo "   └──────────────────────────────────────────────────────────┘"
echo ""
echo ""

echo "🧪 TEST COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Test backend health:"
echo "   $ curl http://localhost:5000/api/health"
echo ""
echo "   Run a simulation:"
echo "   $ curl -X POST http://localhost:5000/api/full-simulation \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"type\":\"infinite-well\",\"parameters\":{\"width\":5,\"num_states\":3}}'"
echo ""
echo "   Test frontend loads:"
echo "   $ curl http://localhost:8000/dashboard.html"
echo ""
echo ""

echo "📍 ACCESS POINTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Backend API:     http://localhost:5000"
echo "   Frontend:        http://localhost:8000/dashboard.html"
echo "   Health Check:    http://localhost:5000/api/health"
echo ""
echo ""

echo "🛠️  HELPFUL COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   View backend logs:"
echo "   $ tail -f /workspaces/animation_quantum_mech_basics/backend.log"
echo ""
echo "   View frontend logs:"
echo "   $ tail -f /workspaces/animation_quantum_mech_basics/app/frontend/public/../../../frontend.log"
echo ""
echo "   Kill all services:"
echo "   $ pkill -f 'python.*enhanced_api\\|python.*http.server'"
echo ""
echo "   Check what's running:"
echo "   $ ps aux | grep python | grep -E '5000|8000'"
echo ""
echo "   Check port usage:"
echo "   $ lsof -i :5000  (for backend)"
echo "   $ lsof -i :8000  (for frontend)"
echo ""
echo ""

echo "📊 WHAT HAPPENS WHEN YOU RUN SIMULATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   1. You open: http://localhost:8000/dashboard.html"
echo "   2. You select: 'Infinite Square Well' from dropdown"
echo "   3. You click: 'Run Simulation' button"
echo "   4. Frontend sends: POST /api/full-simulation (to backend)"
echo "   5. Backend computes: Schrödinger equation solution"
echo "   6. Backend returns: JSON with energy levels, wavefunctions"
echo "   7. Frontend receives: Data in ~100-200ms"
echo "   8. Frontend draws: Plots on canvas"
echo "   9. You see: Energy diagram + Probability plot!"
echo ""
echo ""

echo "✅ VERIFICATION CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   ☐ Backend running?  curl http://localhost:5000/api/health"
echo "   ☐ Frontend loading?  Open http://localhost:8000/dashboard.html"
echo "   ☐ Can see dashboard? (Title, controls, canvases)"
echo "   ☐ Ports forwarded?   (Ports panel shows 5000 & 8000)"
echo "   ☐ Can run sim?       (Select type, click button, plots appear)"
echo "   ☐ No console errors? (F12 to check browser console)"
echo ""
echo ""

echo "🔌 PORT FORWARDING IN CODESPACE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Automatic:"
echo "   - Start service → See notification"
echo "   - Click 'Open in Browser'"
echo "   - Done! ✅"
echo ""
echo "   Manual:"
echo "   - Ctrl+Shift+P → 'Forward a Port'"
echo "   - Enter 5000 (backend)"
echo "   - Enter 8000 (frontend)"
echo "   - Done! ✅"
echo ""
echo "   View Ports:"
echo "   - Click 'Ports' tab at bottom of VS Code"
echo "   - See all forwarded ports"
echo "   - Click globe 🌐 to open in browser"
echo ""
echo ""

echo "❓ COMMON ISSUES & FIXES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Problem: 'Connection refused' on :5000"
echo "   Solution: Check backend is running"
echo "             curl http://localhost:5000/api/health"
echo ""
echo "   Problem: 'Connection refused' on :8000"
echo "   Solution: Check frontend is running"
echo "             curl http://localhost:8000/dashboard.html"
echo ""
echo "   Problem: Frontend loads but 'Can't connect to API'"
echo "   Solution: Open console (F12), check for errors"
echo "             Verify backend: curl http://localhost:5000/api/health"
echo ""
echo "   Problem: Port already in use"
echo "   Solution: Kill process: lsof -i :5000 | grep LISTEN | awk '{print \$2}' | xargs kill -9"
echo ""
echo "   Problem: 'ModuleNotFoundError: No module named..."
echo "   Solution: Activate venv: source .venv/bin/activate"
echo "             Or: pip install <module-name>"
echo ""
echo ""

echo "🎉 YOU'RE READY!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   1. Run:  bash /workspaces/animation_quantum_mech_basics/start_all.sh"
echo "   2. Wait: 'SERVICES STARTED!' message"
echo "   3. Open: Ports panel (bottom of VS Code)"
echo "   4. Click: Globe 🌐 next to port 8000"
echo "   5. Enjoy: Your quantum simulator!"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo ""
